directories:
  output: release
  buildResources: build
appId: com.yourcompany.renoproc
productName: JRENO
asar: false
files:
  - filter:
      - ../src/**/*
      - dist/**/*
  - from: electron
    to: electron
    filter:
      - '**/*'
extraFiles:
  - from: ../resources/poppler
    to: poppler
    filter:
      - '**/*'
electronVersion: 37.2.4
